spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/gb_shop"
    username: "geek"
    password: "geek"
  mvc:
    format:
      date: "yyyy-MM-dd"
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: "geek"
      password: "geek"
logging:
  level:
    org:
      springframework:
        web:    trace
